### PR TITLE
feat: support max-width media query approach

### LINKED ISSUE #61: Feat: option to use max media queries instead of min-width
Hi, I'm currently working on a project that uses `max-width` media queries, which unfortunately makes this module incompatible with our setup.

For instance, in our project, `xs` corresponds to `max-width: 600px`. However, when using this module with the following configuration:
```
  viewport: {
    breakpoints: {
      xs: 600,
      sm: 768,
      md: 1024,
      lg: 1280,
      xl: 1536,
    },

    defaultBreakpoints: {
      desktop: 'lg',
      mobile: 'xs',
      tablet: 'md',
    },

    fallbackBreakpoint: 'lg',
  },
```

The xs breakpoint translates to `(min-width: 1px) and (max-width: 767px)`, which doesn't align with our project's requirements.

This behavior seems to be rooted in the following lines of code: 
https://github.com/mvrlin/nuxt-viewport/blob/4d20486f9a585d6ece7b7d2665f14a6f99e6ff93/src/runtime/manager.ts#L70-L74

It would be immensely beneficial if there was an option to switch between min-width and max-width media queries, allowing for greater flexibility and compatibility with different project requirements.

I am willing to contribute by opening a PR to implement this feature if it aligns with the project's direction.

Thank you,
Meir

### PR DESCRIPTION
**Pull request by meirroth**
This PR adds support to choose between `min-width` or `max-width` approach for media query.

Resolves #61

### CODE REVIEW

**Comment by mvrlin** [comment]
Make a force push to not duplicate commits

**Comment by meirroth** [comment]
@mvrlin Sorry, not sure what you mean 😬

**Comment by mvrlin** [comment]
@meirroth just change the property description as I wrote above 🙂

**Comment by meirroth** [comment]
@mvrlin I'm not seeing your comment 😅 Did you leave a review and not post it maybe?

**Comment by mvrlin** [comment]
> @mvrlin I'm not seeing your comment 😅 Did you leave a review and not post it maybe?

image

**Comment by meirroth** [comment]
@mvrlin Notice how it says pending. You need to click submit review in order for others to see it.
image
Anyway, I fixed as you asked.

**Comment by meirroth** [comment]
@mvrlin Thank you! I look forward to using this in my project once this is released 😃

**Comment by mvrlin** [comment]
@meirroth released https://www.npmjs.com/package/nuxt-viewport/v/2.1.5

**Pull request merged**
